### ISSUE TITLE
Upgrade PostgreSQL in production environment

### ISSUE THREAD

**Issue by hectcastro** [azavea/opendataphilly-ckan#102]
After https://github.com/azavea/opendataphilly-ckan/issues/101 is complete, upgrade PostgreSQL for RDS in staging to match the version selected.

**Comment by rbreslow** [comment]
I verified we're not using any PostgreSQL extensions, so we're [eligible](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion) to upgrade straight to 11.1:

```sql
ckan_default=> \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)
```

I wanted to use the Ansible handlers to restart CKAN, but I happened upon this error during a dry-run (`--check`):

```bash
fatal: [opendataphilly.org]: FAILED! => {"msg": "The conditional check 'pip_version_output | failed or not pip_version_output.stdout | search(pip_version)' failed. The error was: Unexpected templating type error occurred on ({% if
pip_version_output | failed or not pip_version_output.stdout | search(pip_version) %} True {% else %} False {% endif %}): expected string or bytes-like object\n\nThe error appears to be in '/home/rocky/projects/opendataphilly-ckan/
deployment/ansible/roles/azavea.pip/tasks/main.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download get-pip.py\n  ^ here\n"}
```

I believe we'll need to upgrade to the 2.x series of azavea.pip.

---

**Steps to take prior to the upgrade**
- [x] Check for unsupported usage, following the upgrade [docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion)
- [x] Vaccum the database:
```sql
SET maintenance_work_mem='512MB';
\timing
VACUUM (FREEZE, ANALYZE, VERBOSE);
```
- [x] Take a snapshot of the database
- [x] Upgrade to PostgreSQL 9.4.23
- [x] Ensure there is a PostgreSQL 11.4-compatible parameter group ready

**Steps to take during the upgrade**

- [x] Check for unsupported usage, following the upgrade [docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion)
- [x] Vaccum the database:
```sql
SET maintenance_work_mem='512MB';
\timing
VACUUM (FREEZE, ANALYZE, VERBOSE);
```
- [x] Take a snapshot of the database
- [x] Upgrade to PostgreSQL 11.4
- [x] Make sure the parameter group is in-sync
- [x] Restart CKAN:
```bash
sudo service apache2 restart
```

**Steps to take after the upgrade**
- [x] Vaccum the database:
```sql
SET maintenance_work_mem='512MB';
\timing
VACUUM (FREEZE, ANALYZE, VERBOSE);
```
- [x] Upgrade PostgreSQL client libraries

**Comment by hectcastro** [comment]
Looks good. Only note I had was: Instead of the PostgreSQL 9.4.20 -> 11.1 -> 11.4, could we do PostgreSQL 9.4.20 -> 9.4.23 -> 11.4? According to the **Additional Major Version Targets** column, if we're on 9.4.23, we can jump to 11.4.

The latter may require less parameter group wrangling, and I think we can do the 9.4.20 -> 9.4.23 upgrade as soon as we want.
