### ISSUE TITLE
Convert RDS instance type to T3 instance family

### ISSUE THREAD

**Issue by hectcastro** [azavea/opendataphilly-ckan#104]
Currently, the RDS instance type supporting OpenDataPhilly is in the T2 instance family. This issue is to migrate the RDS instance to the T3 instance family.

**Comment by coalkettler** [comment]
This upgrade is scheduled to take place on Monday, May 4th, at 8:00 AM EDT.

**Comment by coalkettler** [comment]
@hectcastro Database instance upgrade is complete. Anything to review here?

**Comment by hectcastro** [comment]
I confirmed that we're on the T3 now. I think this is good to close. 👍
