### ISSUE TITLE
SSL certificate failing to autorenew

### ISSUE THREAD

**Issue by coalkettler** [azavea/opendataphilly-ckan#107]
We had previously resolved a failure in #97, but the certificate still didn't successfully renew on the 25th of this month. Running the crontab command manually was successful. We should figure out why the cron task is failing. Removing the `--quiet` flag from the crontab command may help with debugging.

We're still able to upgrade the SSL certificate and our Panopta alerts are catching when expiry is coming up, so our actual risk is low, but we should get autorenew working again.

**Comment by BryanQuigley** [comment]
Manually changed cron to twice a week and with a random minute offset so it's less likely for let's encrypt to get a lot of rrequests at that specific time.
37 1 * * 2,5 certbot-auto renew --quiet --no-self-upgrade && service nginx reload

**Comment by BryanQuigley** [comment]
Manually changed to:
7 5 * * 2,5 /usr/local/bin/certbot-auto renew --no-self-upgrade >>/var/log/certbot-log 2>&1
13 7 * * 2,5 /usr/bin/service nginx reload >>/var/log/nginx-reload 2>&1
