### ISSUE TITLE
Evaluate upgrade and plugins

### ISSUE THREAD

**Issue by jbranigan** [azavea/opendataphilly-ckan#46]
* Upgrade CKAN to 2.6
* Add/remove images and change sequence of images on landing page
* Perhaps other issues that may have accumulated but are not noted in the ODP repo

Also, estimate what it would take to do this:

> In all of our press releases, we direct people to “opendataphilly.org" to see the open data that’s been released. The trouble is that for users who don’t know what the terms CSV, GeoJSON, API, and Metadata mean, a page like this (https://www.opendataphilly.org/dataset/opa-property-assessments) can be overwhelming and reinforce the belief that “open data is for techies.” We try to put the “Visualization” first, but it doesn’t always stand out much, and still requires you to oddly click a “download” button to access it.
> 
> On the other hand, the “Related” tab further up (below the breadcrumbs) is quite visually engaging and takes you straight to applications that let you explore the data without ever having to download it. So the idea was: what if those “related” items were one of the first things you see on the dataset page, rather than being a bit buried in that tab?
> 
> Well, it turns out it was incredibly easy to do with 8 lines of python code and a bit of boilerplate (folder structure). I’ve created a CKAN plugin out of it:
> https://github.com/CityOfPhiladelphia/ckanext-highlight-related-items (demo: http://45.55.253.172/dataset/opa-property-assessments)
> 
> Joel Natividad was then kind enough to add installation instructions: https://github.com/CityOfPhiladelphia/ckanext-highlight-related-items/pull/1

**Comment by sharph** [comment]
Issues have been created and carded
