### ISSUE TITLE
Add/remove images and change sequence of images on landing page- 0pts

### ISSUE THREAD

**Issue by KlaasH** [azavea/opendataphilly-ckan#50]

**Comment by KlaasH** [comment]
Like https://github.com/azavea/ckanext-odp_theme/pull/49

**Comment by KlaasH** [comment]
@danford1 azavea/ckanext-odp_theme#49 was your handiwork.  Are you able to do what's needed this time around as well?

**Comment by danford1** [comment]
@KlaasH I'm able to do what's needed. Primary objective is to move item in 4th position (within carousel) to the 1st position/default starting position

**Comment by danford1** [comment]
@KlaasH see PRs here: https://github.com/azavea/ckanext-odp_theme/pulls

**Comment by sharph** [comment]
#54 and #55 have been merged
