### ISSUE TITLE
Re-assign datasets owned by JBranigan

### ISSUE THREAD

**Issue by jcahail** [azavea/opendataphilly-ckan#67]
The following datasets are still "owned" by John and can't be edited by anyone else. Please reassign to Kistine Carolan: 
![image](https://cloud.githubusercontent.com/assets/24727081/25351542/eb9d7594-28f6-11e7-9859-6f8bb0cdd3dc.png)

**Comment by sharph** [comment]
Kistine Carolan has been added to the Philadelphia group.
