### ISSUE TITLE
Cut release of ODP theme; update references to use master branch

### ISSUE THREAD

**Issue by hectcastro** [azavea/opendataphilly-ckan#96]
Currently, the provisioning process for CKAN installs the `develop` branch of the [`ckanext-odp_theme`](https://github.com/azavea/ckanext-odp_theme). We should:

- Make the `ckanext-odp_theme` use Git Flow for releases
- Change the default branch for installing the `ckanext-odp_theme` to `master`

**Comment by rcheetham** [comment]
We are archiving this repository as the CKAN instance has been replaced and no new work is planned.
