### ISSUE TITLE
Update City of Phila. logo on "About" page

### ISSUE THREAD

**Issue by stephwall** [azavea/opendataphilly-ckan#98]

**Comment by rcheetham** [comment]
Replace the logo on About with the new one the City has uploaded to the Organization record. Image is at https://www.opendataphilly.org/uploads/group/2019-05-28-133551.204260city-of-philadelphia-bell.png

**Comment by rcheetham** [comment]
Tried to change logo but example City provided doesn't it in the horizontal space on the About page. Asked for a clean PNG with a horizontal layout.

![city-logo-horizontal](https://user-images.githubusercontent.com/595431/59141300-287ef300-8978-11e9-8ae5-2ae7ec981f27.png)

**Comment by rcheetham** [comment]
I received the updated logo. I updated text on the about page, but I don't think I can change the logo easily. The current one is pointing to https://www.opendataphilly.org/img/logo-oit.png

@KlaasH do you know how to change this? Can it be done without a re-deploy?

the new logo is: 
![logo-oit](https://user-images.githubusercontent.com/595431/59813555-f5295600-92df-11e9-87aa-121ebe32eb7f.png)
